name: Bug report
description: Template for bug reports
title: '[Bug]: '
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: dropdown
    id: project
    attributes:
      label: What project is this bug related to?
      options:
        - label: Minecraft Server
          value: project/minecraft-server
        - label: Website
          value: project/website
        - label: History Survival
          value: project/history-survival
        - label: GT MOS
          value: project/gt-mos
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproduction
      description: provide steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception. Error. or logs
      description: provide error logs
    validations:
      required: true
