name: Bug report (Minecraft Server)
description: Template for Minecraft Server bug reports
title: '[Bug (Minecraft Server)]: '
projects:
  - 'miners-online/2'
type: Bug
labels:
  - project/minecraft-server
  - triage
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproduction
      description: provide steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception. Error. or logs
      description: provide error logs
    validations:
      required: true
